Imports System.IO
Imports System.Net

Module GlobalFunctions

    Public Sub CentraliseFormOnScreen(ByRef frm As Form)
        ' position form centrally on screen
        Dim x As Integer = GetLeftPosition(frm)
        Dim y As Integer = GetTopPosition(frm)
        frm.Location = New System.Drawing.Point(x, y)

    End Sub

    Public Function GetLeftPosition(ByVal frm As Form) As Integer
        ' position form
        Dim x As Integer = frm.Width

        Dim Left As Integer
        If varScreenWidth > x Then
            Left = CInt((varScreenWidth - x) / 2)
        Else
            Left = 0
        End If

        Return Left

    End Function

    Public Function GetTopPosition(ByVal frm As Form) As Integer
        ' calculates top position for positioning form on screen
        Dim y As Integer = frm.Height

        Dim Top As Integer

        If varScreenHeight > y Then
            Top = CInt((varScreenHeight - y) / 2)
        Else
            Top = 0
        End If
        Return Top

    End Function

    Public Function CheckForNetwork(Optional ByVal RequestType As Integer = 1) As Boolean
        ' RequestType controls which message to display (or sometimes none at all, message generated by calling program).
        Dim rv As Boolean = False
        Dim ping As New Net.NetworkInformation.Ping
        Dim reply As Net.NetworkInformation.PingReply
        Try
            Dim buf(4) As Byte
            reply = ping.Send("www.gliderscore.com", 2000)
            If reply.Status = Net.NetworkInformation.IPStatus.Success Then
                rv = True
            Else
                If RequestType = 0 Then
                    MsgBox("Network connection to server is not available. Please try again later.")
                ElseIf RequestType = 1 Then
                    MsgBox("Network connection has been lost. Process failed. Please try again later.")
                End If
            End If
        Catch ex As Exception
            'a lot of reasons to be here, but they all mean
            'your internet connection is down
            If RequestType = 0 Then
                MsgBox("Network connection to server is not available. Please try again later.")
            ElseIf RequestType = 1 Then
                MsgBox("Network connection has been lost. Process failed. Please try again later.")
            End If

        End Try
        Return rv

    End Function

    Public Function ExtractWebResponse(ByVal _WebResponse As WebResponse) As String

        Dim _stream As Stream = _WebResponse.GetResponseStream
        Dim _streamReader As New StreamReader(_stream)
        Dim ResponseFromServer As String = _streamReader.ReadLine
        _streamReader.Close()
        Return ResponseFromServer

    End Function
End Module
